"""empty message

Revision ID: 35706a2a306a
Revises: e9349c5ca89a
Create Date: 2019-02-10 12:28:56.948817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35706a2a306a'
down_revision = 'e9349c5ca89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_tag',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.drop_table('password_tag')
    # ### end Alembic commands ###
